# -*- coding: utf-8 -*-
"""deepHack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWBFax7LwFDCQtLncUPIJKf-ODAwN9Su
"""



from zipfile import ZipFile
from io import BytesIO
from urllib.request import urlopen
import pandas
from google.colab import files
import matplotlib.pyplot as plt

address = "https://transparencia.tce.sp.gov.br/iegm-deephack2019"
file = urlopen(address)
zf = ZipFile(BytesIO(file.read()))
df = pandas.read_csv(zf.open('iegm.csv'), encoding='latin-1', error_bad_lines = False, sep = ';')



"""# IEGM"""

df.head()

df.columns

ambDF = df.loc[df['indice'] == 'i-Amb']
ambDF = df.drop(columns=['cod_ibge', 'municipio', 'porte', 'ano_exercicio', 'indice'])
ambDF['rotulo_resposta'].value_counts()

pandas.options.display.max_rows = 200
 pandas.options.display.max_colwidth = 300

ambDF['texto_pergunta_genérica'].value_counts()

ambDF['valor_resposta'].value_counts()



"""# JSON API"""

from google.colab import drive
drive.mount('/content/drive')

despesasDF = pandas.read_json('https://transparencia.tce.sp.gov.br/api/json/despesas/jarinu/2015/1')
despesasDF.vl_despesa.astype('str')
despesasDF['vl_despesa'] = despesasDF['vl_despesa'].apply(lambda x: float(x.replace(',', '.')))
despesasDF.head()

despesasEmpDF = despesasDF[despesasDF['evento'] == 'Empenhado']
despesasEmpDF.head()

print('R$ {:.2f}'.format(float(sum(despesasEmpDF.vl_despesa))))

